name: Update Version Badge

on:
  release:
    types: [published]

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Tag Name
        id: pre
        run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i 's|.*|![Release](https://img.shields.io/badge/release-${{ env.VERSION }}-blue?style=for-the-badge)|g' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update release badge to ${{ env.VERSION }} [skip ci]" || exit 0
          git push